# Generated by Django 5.0.6 on 2024-06-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_car_description_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('can_add_product', 'Can add product'), ('can_change_product', 'Can change product'), ('can_delete_product', 'Can delete product')]},
        ),
    ]
